### ISSUE TITLE
Error message while running

### ISSUE THREAD

**Issue by wjcoats** [rlemm-pan/userid-check#3]
## Steps to reproduce

1. run the command python3 userid-check.py or python3 userid-check.py -h
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Python 3.12
- Operating System and version (desktop or mobile): Windows 11
- Link to your project: NA

**Comment by rlemm-pan** [comment]
could you please provide the error you were receiving?  Thanks...

**Comment by wjcoats** [comment]
Here is what I am receiving.

C:\Users\william.coats\Downloads\userid-check-main>python3 userid-check.py -h
Traceback (most recent call last):
  File "C:\Users\william.coats\Downloads\userid-check-main\userid-check.py", line 14, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'


C:\Users\william.coats\Downloads\userid-check-main>python3 userid-check.py
Traceback (most recent call last):
  File "C:\Users\william.coats\Downloads\userid-check-main\userid-check.py", line 14, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

Thank you

Wiilliam Coats
________________________________

**Comment by rlemm-pan** [comment]
there is a requirements.txt reference to which modules are required.  Please run this command to install them:

pip install -r requirements.txt

or

pip3 install -r requirements.txt

**Comment by wjcoats** [comment]
I have run this command.  That gives an error message.  Here is the error message: ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\william.coats\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\pkg_resources\\tests\\data\\my-test-package_unpacked-egg\\my_test_package-1.0-py3.7.egg\\EGG-INFO\\dependency_links.txt'

Thank you.

William Coats
________________________________

**Comment by rlemm-pan** [comment]
It might be that python is not in your path or pip is not installed.  This might help:

If you are facing any path error then you can follow the following steps to add the pip to your PATH. You can follow the following steps to adding pip to path windows 10 and set the Path:

- Go to System and Security > System in the Control Panel once it has been opened.
- On the left side, click the Advanced system settings link.
- Then select Environment Variables.
- Double-click the PATH variable under System Variables.
- Click New, and add the directory where pip is installed, and select OK.
