### ISSUE TITLE
10.1.13 and above are listed as both supported + unsupported

### ISSUE THREAD

**Issue by thelastmike** [rlemm-pan/userid-check#4]
## Describe the bug

Table 2 on https://live.paloaltonetworks.com/t5/customer-advisories/update-to-additional-pan-os-certificate-expirations-and-new/ta-p/572158 shows **10.1.12 or newer** as being the "*Minimum Target Version*", however 10.1.13, 10.1.14 and 10.1.14-h2 are listed in both the `supported_panos_versions` and the `unsupported_panos_versions` lists.

## Expected behavior

10.1.13, 10.1.14 and 10.1.14-h2 should appear as devices under the pretty green section for "*PANOS Devices with Agents are on a Supported PANOS Version*".

## Current behavior

They instead appear in yellow under the section for "*PANOS Devices with Agents that require PANOS Upgrades*", but have no value in the column for `Suggested PANOS Version`.

## Possible solution

Remove the overlapping values from line 78 of `userid-check.py`. https://github.com/PaloAltoNetworks/userid-check/blob/655c87f86fceda39005b6c2009970519014edf1d/userid-check.py#L78

## Steps to reproduce

Run against a device reporting one of the affected versions. (A quick `print(set(supported_panos_versions) & set(unsupported_panos_versions))` indicates these are the only three in both lists.)

## Context

This makes for a pretty confusing user experience, since the output contradicts the documentation linked above.

**Comment by rlemm-pan** [comment]
This has been a moving target.  I will update the list and push within the next 24 hrs.

**Comment by rlemm-pan** [comment]
Removed 10.1.13, 10.1.14, 10.1.14-h2.  closing issue
