### ISSUE TITLE
Missing requirement to use the tool

### ISSUE THREAD

**Issue by MattiaSoranzoSintesi** [rlemm-pan/userid-check#5]
## Documentation link

Before we dive in, let's go over the prerequisites for using this tool. First, make sure you're running Python version 3.x or greater on the host you will be using to run this tool

## Describe the problem

With the current requirements the users will face a problem executing the command `pip install -r requirements.txt` when the melson library will try to compile but there wont be any compiler installed on the machine.

## Suggested fix

Notify the users to prevent those errors installing Visual Studio Build Tools and enabling the "Desktop Application Development with C++" flag.
That operation will install all the necessary compilers to correctly compile the melson library.

![immagine](https://github.com/user-attachments/assets/d4d31f36-1a13-4f49-be14-6f4fe67a86f1)

**Comment by rlemm-pan** [comment]
Added Suggested fix to README.md
