### ISSUE TITLE
Received invalid response. Agent not responding.

### ISSUE THREAD

**Issue by Nostalgiac** [rlemm-pan/userid-check#6]
## Describe the bug

When runnign the tool it shows the following error after entering valid credentials.  No details are populated in the table below it, fails to output any details in diagram or html output.

Received invalid response. Agent not responding. Skipping IP [x.x.x.x]

## Steps to reproduce

1. python userid-check.py
2. Enter filename of the document with IP in it
3. Enter login name
4. Enter password

## Screenshots
![image](https://github.com/user-attachments/assets/cfa6f154-9c83-42b6-9806-e7a1d3afbb67)

## Context

Software Version	11.0.3-h10

**Comment by rlemm-pan** [comment]
The agent has to be accessible / reachable from where the tool is being executed.  Check to make sure the Microsoft platform that the agent is running on can be accessed on port 5007 from your host that is running the tool.
